In [1]:
import pandas as pd

In [5]:
data = pd.Series([1,2],index=['a','b'])
data

a    1
b    2
dtype: int64

In [6]:
data = pd.DataFrame([1,2,3,4,5,6])
data

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [ ]:

#data frame

In [9]:
st = ([1,2,3,4,5],[1,3,5,7,9])
df = pd.DataFrame(st)
df

   0  1  2  3  4
0  1  2  3  4  5
1  1  3  5  7  9

In [10]:
#dictionary

In [12]:
dict = {'name':['kamal','saman','nimal'],'marks':[80,60,70]}
df = pd.DataFrame(dict)
df

    name  marks
0  kamal     80
1  saman     60
2  nimal     70

In [13]:
# how to couple two dataframe

In [16]:
dict1 = {'sasin':[40,50,60],'ruchika':[80,60,70]}
df1 = pd.DataFrame(dict1)

dict2 = {'nayon':[45,80,70],'hirun':[86,90,10]}
df2 = pd.DataFrame(dict2)

In [17]:
df1

   sasin  ruchika
0     40       80
1     50       60
2     60       70

In [18]:
df2

   nayon  hirun
0     45     86
1     80     90
2     70     10

In [19]:
pd.concat([df1,df2])

   sasin  ruchika  nayon  hirun
0   40.0     80.0    NaN    NaN
1   50.0     60.0    NaN    NaN
2   60.0     70.0    NaN    NaN
0    NaN      NaN   45.0   86.0
1    NaN      NaN   80.0   90.0
2    NaN      NaN   70.0   10.0

In [20]:
pd.concat([df1,df2],axis=1)

   sasin  ruchika  nayon  hirun
0     40       80     45     86
1     50       60     80     90
2     60       70     70     10